# Generated by Django 5.0.7 on 2024-07-12 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CellPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('problem_description', models.TextField()),
                ('diagnosis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('primary_phone_number', models.CharField(max_length=20)),
                ('secondary_phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='itsc_celulares.cellphone')),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RepairOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('RECEIVED', 'Recibido'), ('IN DIAGNOSIS', 'En Diagnostico'), ('IN REPAIR', 'En Reparacion'), ('READY FOR DELIVERY', 'Listo para entrega'), ('DELIVERED', 'Entregado')], default='RECEIVED', max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='itsc_celulares.customer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='itsc_celulares.cellphone')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='itsc_celulares.technician')),
            ],
        ),
    ]
